import { UserProfile } from '@renderer/types/users';
import {
  DemoItem,
  FileFormat,
  ItemType,
} from '../../types/items'; // <-- Replace with the actual path to your types
import { FileTag } from "@renderer/types/tags";

export const friendsData: UserProfile[] = [
    { id: "1", username: "lisa", name: "Lisa Simpson", avatar: null, description: "Loves jazz music." },
    { id: "2", username: "bart", name: "Bart Simpson", avatar: null, description: "Prankster in chief." },
    { id: "3", username: "maggie", name: "Maggie Simpson", avatar: null, description: "Silent but wise." },
    { id: "4", username: "milhouse", name: "Milhouse Van Houten", avatar: null, description: "Bart's best friend." },
    { id: "5", username: "moe", name: "Moe Szyslak", avatar: null, description: "Owns Moe's Tavern." },
    { id: "6", username: "skinner", name: "Seymour Skinner", avatar: null, description: "Principal at Springfield Elementary." },
    ];

export const currentUser: UserProfile = {
    id: "9012012810291",
    username: "juanlucasumali",
    name: "Juan Lucas Umali",
    avatar: null,
    description: "OBSESSED with jazz.",
}

export const dummyDemoItems: DemoItem[] = [
  {
    id: "folder-001",
    createdAt: new Date("2024-01-01T12:00:00Z"),
    lastOpened: new Date("2024-01-05T08:00:00Z"),
    lastModified: new Date("2024-01-05T08:00:00Z"),
    name: "Vocal Recordings",
    isStarred: false,
    tags: FileTag.Recording,
    projectId: "project-001",
    parentFolderId: "root",
    filePath: "/project-001/Vocal Recordings",
    owner: currentUser,
    sharedWith: [friendsData[0], friendsData[1], friendsData[2], friendsData[3], friendsData[4], friendsData[5]],
    type: ItemType.FOLDER,
    format: null,
    size: null,
    duration: null,
    description: "Collection of vocal recordings for the project",
    icon: null,
    collectionId: null,
  },
  {
    id: "file-101",
    createdAt: new Date("2024-01-02T10:15:00Z"),
    lastOpened: new Date("2024-01-05T08:00:00Z"),
    lastModified: new Date("2024-01-03T11:20:00Z"),
    name: "LeadVocal_Take1",
    isStarred: false,
    tags: FileTag.Recording,
    projectId: "project-001",
    parentFolderId: "folder-001",
    filePath: "/project-001/Vocal Recordings/LeadVocal_Take1.mp3",
    owner: currentUser,
    sharedWith: [friendsData[2], friendsData[3]],
    format: FileFormat.MP3,
    size: 3_150_000,
    duration: 180,
    type: ItemType.FILE,
    description: "First take of the lead vocals",
    icon: null,
    collectionId: null,
  },
  {
    id: "folder-002",
    createdAt: new Date("2024-02-10T09:00:00Z"),
    lastOpened: new Date("2024-01-05T08:00:00Z"),
    lastModified: new Date("2024-02-12T07:30:00Z"),
    name: "Instrumentals",
    isStarred: true,
    tags: FileTag.Stems,
    projectId: "project-001",
    parentFolderId: "root",
    filePath: "/project-001/Instrumentals",
    owner: currentUser,
    sharedWith: [friendsData[4], friendsData[5]],
    type: ItemType.FOLDER,
    format: null,
    size: null,
    duration: null,
    description: "All instrumental stems and recordings",
    icon: null,
    collectionId: null,
  },
  {
    id: "file-201",
    createdAt: new Date("2024-02-10T09:05:00Z"),
    lastOpened: new Date("2024-01-05T08:00:00Z"),
    lastModified: new Date("2024-02-10T09:06:00Z"),
    name: "GuitarStem.wav",
    isStarred: false,
    tags: FileTag.Stems,
    projectId: "project-001",
    parentFolderId: "folder-002",
    filePath: "/project-001/Instrumentals/GuitarStem.wav",
    owner: currentUser,
    sharedWith: [friendsData[0], friendsData[2], friendsData[4]],
    format: FileFormat.WAV,
    size: 6_200_000,
    duration: 240,
    type: ItemType.FILE,
    description: "Clean guitar stem recording",
    icon: null,
    collectionId: null,
  },
  {
    id: "file-202",
    createdAt: new Date("2024-02-11T10:00:00Z"),
    lastOpened: new Date("2024-01-05T08:00:00Z"),
    lastModified: new Date("2024-02-11T12:45:00Z"),
    name: "DrumsStem_v2",
    isStarred: false,
    tags: FileTag.Stems,
    projectId: "project-001",
    parentFolderId: "folder-002",
    filePath: "/project-001/Instrumentals/DrumsStem_v2.wav",
    owner: currentUser,
    sharedWith: [friendsData[1], friendsData[3], friendsData[5]],
    format: FileFormat.WAV,
    size: 8_400_000,
    duration: 210,
    type: ItemType.FILE,
    description: "Second version of the drum stem",
    icon: null,
    collectionId: null,
  },
  {
    id: "folder-003",
    createdAt: new Date("2024-03-01T08:00:00Z"),
    lastOpened: new Date("2024-01-05T08:00:00Z"),
    lastModified: new Date("2024-03-05T18:00:00Z"),
    name: "Final Mixes",
    isStarred: true,
    tags: FileTag.Mix,
    projectId: "project-001",
    parentFolderId: "root",
    filePath: "/project-001/Final Mixes",
    owner: currentUser,
    sharedWith: [friendsData[0], friendsData[1], friendsData[2]],
    type: ItemType.FOLDER,
    format: null,
    size: null,
    duration: null,
    description: "Final mixed versions of the tracks",
    icon: null,
    collectionId: null,
  },
  {
    id: "file-301",
    createdAt: new Date("2024-03-02T14:30:00Z"),
    lastOpened: new Date("2024-01-05T08:00:00Z"),
    lastModified: new Date("2024-03-03T09:00:00Z"),
    name: "AlbumVersion_MasterAlbumVersion_MasterAlbumVersion_Master.mp3",
    isStarred: false,
    tags: FileTag.Master,
    projectId: "project-001",
    parentFolderId: "folder-003",
    filePath: "/project-001/Final Mixes/AlbumVersion_Master.mp3",
    owner: currentUser,
    sharedWith: [friendsData[3], friendsData[4], friendsData[5]],
    format: FileFormat.MP3,
    size: 9_100_000,
    duration: 200,
    type: ItemType.FILE,
    description: "Mastered version for the album",
    icon: null,
    collectionId: null,
  },
  {
    id: "folder-004",
    createdAt: new Date("2024-03-15T11:00:00Z"),
    lastOpened: new Date("2024-03-20T14:00:00Z"),
    lastModified: new Date("2024-03-18T16:00:00Z"),
    name: "Project Ideas",
    isStarred: true,
    tags: FileTag.Reference,
    projectId: "project-001",
    parentFolderId: "root",
    filePath: "/project-001/Project Ideas",
    owner: currentUser,
    sharedWith: [friendsData[2], friendsData[4]],
    type: ItemType.FOLDER,
    format: null,
    size: null,
    duration: null,
    description: "Folder containing brainstorming and concept files",
    icon: null,
    collectionId: null,
  },
  {
    id: "file-401",
    createdAt: new Date("2024-03-16T09:30:00Z"),
    lastOpened: new Date("2024-03-17T10:00:00Z"),
    lastModified: new Date("2024-03-16T15:00:00Z"),
    name: "ConceptSketch.pdf",
    isStarred: false,
    tags: FileTag.Reference,
    projectId: "project-001",
    parentFolderId: "folder-004",
    filePath: "/project-001/Project Ideas/ConceptSketch.pdf",
    owner: currentUser,
    sharedWith: [friendsData[1], friendsData[3]],
    format: FileFormat.ZIP,
    size: 2_400_000,
    duration: null,
    type: ItemType.FILE,
    description: "Initial concept sketches for the project",
    icon: null,
    collectionId: null,
  },
  {
    id: "file-402",
    createdAt: new Date("2024-03-18T13:00:00Z"),
    lastOpened: new Date("2024-03-19T14:30:00Z"),
    lastModified: new Date("2024-03-18T17:00:00Z"),
    name: "BudgetSheet.xlsx",
    isStarred: false,
    tags: FileTag.Reference,
    projectId: "project-001",
    parentFolderId: "folder-004",
    filePath: "/project-001/Project Ideas/BudgetSheet.xlsx",
    owner: currentUser,
    sharedWith: [friendsData[0], friendsData[5]],
    format: FileFormat.WAV,
    size: 1_200_000,
    duration: null,
    type: ItemType.FILE,
    description: "Budget planning sheet for the project",
    icon: null,
    collectionId: null,
  },
  {
    id: "folder-005",
    createdAt: new Date("2024-04-01T09:00:00Z"),
    lastOpened: new Date("2024-04-05T08:00:00Z"),
    lastModified: new Date("2024-04-04T15:00:00Z"),
    name: "Reference Tracks",
    isStarred: true,
    tags: FileTag.Reference,
    projectId: "project-001",
    parentFolderId: "root",
    filePath: "/project-001/Reference Tracks",
    owner: currentUser,
    sharedWith: [friendsData[1], friendsData[3], friendsData[4]],
    type: ItemType.FOLDER,
    format: null,
    size: null,
    duration: null,
    description: "Tracks used as references for inspiration",
    icon: null,
    collectionId: null,
  },
  {
    id: "file-501",
    createdAt: new Date("2024-04-02T12:00:00Z"),
    lastOpened: new Date("2024-04-05T09:30:00Z"),
    lastModified: new Date("2024-04-03T12:30:00Z"),
    name: "InspirationTrack.mp3",
    isStarred: false,
    tags: FileTag.Reference,
    projectId: "project-001",
    parentFolderId: "folder-005",
    filePath: "/project-001/Reference Tracks/InspirationTrack.mp3",
    owner: currentUser,
    sharedWith: [friendsData[2], friendsData[5]],
    format: FileFormat.MP3,
    size: 5_300_000,
    duration: 220,
    type: ItemType.FILE,
    description: "Track that served as a reference for the project's style",
    icon: null,
    collectionId: null,
  },
  {
    id: "file-502",
    createdAt: new Date("2024-04-04T10:30:00Z"),
    lastOpened: new Date("2024-04-05T14:00:00Z"),
    lastModified: new Date("2024-04-04T13:45:00Z"),
    name: "VocalProcessingGuide.pdf",
    isStarred: false,
    tags: FileTag.Reference,
    projectId: "project-001",
    parentFolderId: "folder-005",
    filePath: "/project-001/Reference Tracks/VocalProcessingGuide.pdf",
    owner: currentUser,
    sharedWith: [friendsData[0], friendsData[3]],
    format: FileFormat.MP4,
    size: 1_500_000,
    duration: null,
    type: ItemType.FILE,
    description: "Guide for vocal processing techniques",
    icon: null,
    collectionId: null,
  },
  {
    id: "folder-006",
    createdAt: new Date("2024-05-10T10:00:00Z"),
    lastOpened: new Date("2024-05-15T11:00:00Z"),
    lastModified: new Date("2024-05-14T14:00:00Z"),
    name: "Unused Tracks",
    isStarred: false,
    tags: FileTag.ProjectFile,
    projectId: "project-001",
    parentFolderId: "root",
    filePath: "/project-001/Unused Tracks",
    owner: currentUser,
    sharedWith: [],
    type: ItemType.FOLDER,
    format: null,
    size: null,
    duration: null,
    description: "Tracks not used in the final production",
    icon: null,
    collectionId: null,
  },
  {
    id: "file-601",
    createdAt: new Date("2024-05-11T14:30:00Z"),
    lastOpened: new Date("2024-05-12T16:00:00Z"),
    lastModified: new Date("2024-05-11T15:30:00Z"),
    name: "AltVersion1.wav",
    isStarred: false,
    tags: FileTag.Stems,
    projectId: "project-001",
    parentFolderId: "folder-006",
    filePath: "/project-001/Unused Tracks/AltVersion1.wav",
    owner: currentUser,
    sharedWith: [friendsData[0]],
    format: FileFormat.WAV,
    size: 7_800_000,
    duration: 260,
    type: ItemType.FILE,
    description: "An alternate version of the track",
    icon: null,
    collectionId: null,
  },
  {
    id: "file-602",
    createdAt: new Date("2024-05-12T10:00:00Z"),
    lastOpened: new Date("2024-05-15T14:30:00Z"),
    lastModified: new Date("2024-05-12T12:30:00Z"),
    name: "SynthExperiment.mp3",
    isStarred: false,
    tags: FileTag.Stems,
    projectId: "project-001",
    parentFolderId: "folder-006",
    filePath: "/project-001/Unused Tracks/SynthExperiment.mp3",
    owner: currentUser,
    sharedWith: [friendsData[2], friendsData[5]],
    format: FileFormat.MP3,
    size: 4_500_000,
    duration: 180,
    type: ItemType.FILE,
    description: "Experimental synth-based track",
    icon: null,
    collectionId: null,
  },
];

export const dummyProjectItems: DemoItem[] = [
    {
      id: "project-001",
      createdAt: new Date("2024-01-01T10:00:00Z"),
      lastOpened: new Date("2024-03-20T15:30:00Z"),
      lastModified: new Date("2024-03-20T15:30:00Z"),
      name: "Midnight Echoes",
      isStarred: true,
      tags: FileTag.ProjectFile,
      projectId: null,
      parentFolderId: null,
      filePath: null,
      owner: currentUser,
      sharedWith: [friendsData[0], friendsData[1], friendsData[2]],
      type: ItemType.PROJECT,
      format: null,
      size: null,
      duration: null,
      description: "Dark R&B track with atmospheric electronic elements",
      icon: null,
      collectionId: null,
    },
    {
      id: "project-002",
      createdAt: new Date("2024-02-15T09:00:00Z"),
      lastOpened: new Date("2024-03-19T14:00:00Z"),
      lastModified: new Date("2024-03-19T14:00:00Z"),
      name: "Urban Pulse",
      isStarred: false,
      tags: FileTag.ProjectFile,
      projectId: null,
      parentFolderId: null,
      filePath: null,
      owner: currentUser,
      sharedWith: [friendsData[3], friendsData[4]],
      type: ItemType.PROJECT,
      format: null,
      size: null,
      duration: null,
      description: "High-energy trap beat with drill influences",
      icon: null,
      collectionId: null,
    },
    {
      id: "project-003",
      createdAt: new Date("2024-03-01T11:00:00Z"),
      lastOpened: new Date("2024-03-18T16:45:00Z"),
      lastModified: new Date("2024-03-18T16:45:00Z"),
      name: "Ethereal Dreams",
      isStarred: true,
      tags: FileTag.ProjectFile,
      projectId: null,
      parentFolderId: null,
      filePath: null,
      owner: currentUser,
      sharedWith: [friendsData[0], friendsData[5], friendsData[1], friendsData[2], friendsData[4]],
      type: ItemType.PROJECT,
      format: null,
      size: null,
      duration: null,
      description: "Ambient soundscape with ethereal synths and textures",
      icon: null,
      collectionId: null,
    },
    {
      id: "project-004",
      createdAt: new Date("2024-03-10T13:30:00Z"),
      lastOpened: new Date("2024-03-17T10:20:00Z"),
      lastModified: new Date("2024-03-17T10:20:00Z"),
      name: "Jazz Fusion Experiment",
      isStarred: false,
      tags: FileTag.ProjectFile,
      projectId: null,
      parentFolderId: null,
      filePath: null,
      owner: currentUser,
      sharedWith: [friendsData[1], friendsData[2], friendsData[4], friendsData[5]],
      type: ItemType.PROJECT,
      format: null,
      size: null,
      duration: null,
      description: "Modern jazz fusion with electronic elements",
      icon: null,
      collectionId: null,
    },
    {
      id: "project-005",
      createdAt: new Date("2024-03-15T16:00:00Z"),
      lastOpened: new Date("2024-03-16T09:15:00Z"),
      lastModified: new Date("2024-03-16T09:15:00Z"),
      name: "Synthwave Nights",
      isStarred: true,
      tags: FileTag.ProjectFile,
      projectId: null,
      parentFolderId: null,
      filePath: null,
      owner: currentUser,
      sharedWith: [friendsData[3], friendsData[5], friendsData[0], friendsData[1], friendsData[2], friendsData[4]],
      type: ItemType.PROJECT,
      format: null,
      size: null,
      duration: null,
      description: "80s inspired synthwave with modern production",
      icon: null,
      collectionId: null,
    }
  ]