import { UserProfile } from '@renderer/types/users';
import {
  DemoItem,
  FileFormat,
} from '../../types/items'; // <-- Replace with the actual path to your types
import { FileTag } from "@renderer/types/tags";

export const friendsData: UserProfile[] = [
    { id: "1", username: "lisa", name: "Lisa Simpson", avatar: null, email: "lisa@example.com", description: "Loves jazz music." },
    { id: "2", username: "bart", name: "Bart Simpson", avatar: null, email: "bart@example.com", description: "Prankster in chief." },
    { id: "3", username: "maggie", name: "Maggie Simpson", avatar: null, email: "maggie@example.com", description: "Silent but wise." },
    { id: "4", username: "milhouse", name: "Milhouse Van Houten", avatar: null, email: "milhouse@example.com", description: "Bart's best friend." },
    { id: "5", username: "moe", name: "Moe Szyslak", avatar: null, email: "moe@example.com", description: "Owns Moe's Tavern." },
    { id: "6", username: "skinner", name: "Seymour Skinner", avatar: null, email: "skinner@example.com", description: "Principal at Springfield Elementary." },
    ];

export const currentUser: UserProfile = {
    id: "9012012810291",
    username: "juanlucasumali",
    name: "Juan Lucas Umali",
    avatar: null,
    email: "juanlucasumali@gmail.com",
    description: "OBSESSED with jazz.",
}

export const dummyDemoItems: DemoItem[] = [
  {
      id: "folder-001",
      createdAt: new Date("2024-01-01T12:00:00Z"),
      lastOpened: new Date("2024-01-05T08:00:00Z"),
      lastModified: new Date("2024-01-05T08:00:00Z"),
      name: "Vocal Recordings",
      isStarred: false,
      tags: FileTag.Recording,
      projectId: "project-abc",
      parentFolderId: "root",
      filePath: "/project-abc/Vocal Recordings",
      owner: currentUser,
      sharedWith: [friendsData[0], friendsData[1]],
      type: "folder",
      format: null,
      size: null,
      duration: null,
  },
  {
      id: "file-101",
      createdAt: new Date("2024-01-02T10:15:00Z"),
      lastOpened: new Date("2024-01-05T08:00:00Z"),
      lastModified: new Date("2024-01-03T11:20:00Z"),
      name: "LeadVocal_Take1",
      isStarred: false,
      tags: FileTag.Recording,
      projectId: "project-abc",
      parentFolderId: "folder-001",
      filePath: "/project-abc/Vocal Recordings/LeadVocal_Take1.mp3",
      owner: currentUser,
      sharedWith: [friendsData[2], friendsData[3]],
      format: FileFormat.MP3,
      size: 3_150_000,
      duration: 180,
      type: "file",
  },
  {
      id: "folder-002",
      createdAt: new Date("2024-02-10T09:00:00Z"),
      lastOpened: new Date("2024-01-05T08:00:00Z"),
      lastModified: new Date("2024-02-12T07:30:00Z"),
      name: "Instrumentals",
      isStarred: true,
      tags: FileTag.Stems,
      projectId: "project-abc",
      parentFolderId: "root",
      filePath: "/project-abc/Instrumentals",
      owner: currentUser,
      sharedWith: [friendsData[4], friendsData[5]],
      type: "folder",
      format: null,
      size: null,
      duration: null,
  },
  {
      id: "file-201",
      createdAt: new Date("2024-02-10T09:05:00Z"),
      lastOpened: new Date("2024-01-05T08:00:00Z"),
      lastModified: new Date("2024-02-10T09:06:00Z"),
      name: "GuitarStem.wav",
      isStarred: false,
      tags: FileTag.Stems,
      projectId: "project-abc",
      parentFolderId: "folder-002",
      filePath: "/project-abc/Instrumentals/GuitarStem.wav",
      owner: currentUser,
      sharedWith: [friendsData[0], friendsData[2], friendsData[4]],
      format: FileFormat.WAV,
      size: 6_200_000,
      duration: 240,
      type: "file",
  },
  {
      id: "file-202",
      createdAt: new Date("2024-02-11T10:00:00Z"),
      lastOpened: new Date("2024-01-05T08:00:00Z"),
      lastModified: new Date("2024-02-11T12:45:00Z"),
      name: "DrumsStem_v2",
      isStarred: false,
      tags: FileTag.Stems,
      projectId: "project-abc",
      parentFolderId: "folder-002",
      filePath: "/project-abc/Instrumentals/DrumsStem_v2.wav",
      owner: currentUser,
      sharedWith: [friendsData[1], friendsData[3], friendsData[5]],
      format: FileFormat.WAV,
      size: 8_400_000,
      duration: 210,
      type: "file",
  },
  {
      id: "folder-003",
      createdAt: new Date("2024-03-01T08:00:00Z"),
      lastOpened: new Date("2024-01-05T08:00:00Z"),
      lastModified: new Date("2024-03-05T18:00:00Z"),
      name: "Final Mixes",
      isStarred: true,
      tags: FileTag.Mix,
      projectId: "project-abc",
      parentFolderId: "root",
      filePath: "/project-abc/Final Mixes",
      owner: currentUser,
      sharedWith: [friendsData[0], friendsData[1], friendsData[2]],
      type: "folder",
      format: null,
      size: null,
      duration: null,
  },
  {
      id: "file-301",
      createdAt: new Date("2024-03-02T14:30:00Z"),
      lastOpened: new Date("2024-01-05T08:00:00Z"),
      lastModified: new Date("2024-03-03T09:00:00Z"),
      name: "AlbumVersion_Master.mp3",
      isStarred: false,
      tags: FileTag.Master,
      projectId: "project-abc",
      parentFolderId: "folder-003",
      filePath: "/project-abc/Final Mixes/AlbumVersion_Master.mp3",
      owner: currentUser,
      sharedWith: [friendsData[3], friendsData[4], friendsData[5]],
      format: FileFormat.MP3,
      size: 9_100_000,
      duration: 200,
      type: "file",
  },
];