/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProjectsIndexImport } from './routes/projects/index'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as IntegrationsIndexImport } from './routes/integrations/index'
import { Route as HomeIndexImport } from './routes/home/index'
import { Route as CreateProfileIndexImport } from './routes/create-profile/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as ProjectsProjectIdIndexImport } from './routes/projects/$projectId/index'
import { Route as IntegrationsIntegrationIdIndexImport } from './routes/integrations/$integrationId/index'
import { Route as HomeFoldersFolderIdImport } from './routes/home/folders/$folderId'
import { Route as ProjectsProjectIdCollectionIdIndexImport } from './routes/projects/$projectId/$collectionId/index'

// Create/Update Routes

const ProjectsIndexRoute = ProjectsIndexImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any)

const IntegrationsIndexRoute = IntegrationsIndexImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRoute,
} as any)

const CreateProfileIndexRoute = CreateProfileIndexImport.update({
  id: '/create-profile/',
  path: '/create-profile/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRoute,
} as any)

const IntegrationsIntegrationIdIndexRoute =
  IntegrationsIntegrationIdIndexImport.update({
    id: '/integrations/$integrationId/',
    path: '/integrations/$integrationId/',
    getParentRoute: () => rootRoute,
  } as any)

const HomeFoldersFolderIdRoute = HomeFoldersFolderIdImport.update({
  id: '/home/folders/$folderId',
  path: '/home/folders/$folderId',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectIdCollectionIdIndexRoute =
  ProjectsProjectIdCollectionIdIndexImport.update({
    id: '/projects/$projectId/$collectionId/',
    path: '/projects/$projectId/$collectionId/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/create-profile/': {
      id: '/create-profile/'
      path: '/create-profile'
      fullPath: '/create-profile'
      preLoaderRoute: typeof CreateProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof rootRoute
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexImport
      parentRoute: typeof rootRoute
    }
    '/home/folders/$folderId': {
      id: '/home/folders/$folderId'
      path: '/home/folders/$folderId'
      fullPath: '/home/folders/$folderId'
      preLoaderRoute: typeof HomeFoldersFolderIdImport
      parentRoute: typeof rootRoute
    }
    '/integrations/$integrationId/': {
      id: '/integrations/$integrationId/'
      path: '/integrations/$integrationId'
      fullPath: '/integrations/$integrationId'
      preLoaderRoute: typeof IntegrationsIntegrationIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId/$collectionId/': {
      id: '/projects/$projectId/$collectionId/'
      path: '/projects/$projectId/$collectionId'
      fullPath: '/projects/$projectId/$collectionId'
      preLoaderRoute: typeof ProjectsProjectIdCollectionIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/auth': typeof AuthIndexRoute
  '/create-profile': typeof CreateProfileIndexRoute
  '/home': typeof HomeIndexRoute
  '/integrations': typeof IntegrationsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/home/folders/$folderId': typeof HomeFoldersFolderIdRoute
  '/integrations/$integrationId': typeof IntegrationsIntegrationIdIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/$collectionId': typeof ProjectsProjectIdCollectionIdIndexRoute
}

export interface FileRoutesByTo {
  '/auth': typeof AuthIndexRoute
  '/create-profile': typeof CreateProfileIndexRoute
  '/home': typeof HomeIndexRoute
  '/integrations': typeof IntegrationsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/home/folders/$folderId': typeof HomeFoldersFolderIdRoute
  '/integrations/$integrationId': typeof IntegrationsIntegrationIdIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/$collectionId': typeof ProjectsProjectIdCollectionIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/auth/': typeof AuthIndexRoute
  '/create-profile/': typeof CreateProfileIndexRoute
  '/home/': typeof HomeIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/home/folders/$folderId': typeof HomeFoldersFolderIdRoute
  '/integrations/$integrationId/': typeof IntegrationsIntegrationIdIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/$collectionId/': typeof ProjectsProjectIdCollectionIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/create-profile'
    | '/home'
    | '/integrations'
    | '/profile'
    | '/projects'
    | '/home/folders/$folderId'
    | '/integrations/$integrationId'
    | '/projects/$projectId'
    | '/projects/$projectId/$collectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/create-profile'
    | '/home'
    | '/integrations'
    | '/profile'
    | '/projects'
    | '/home/folders/$folderId'
    | '/integrations/$integrationId'
    | '/projects/$projectId'
    | '/projects/$projectId/$collectionId'
  id:
    | '__root__'
    | '/auth/'
    | '/create-profile/'
    | '/home/'
    | '/integrations/'
    | '/profile/'
    | '/projects/'
    | '/home/folders/$folderId'
    | '/integrations/$integrationId/'
    | '/projects/$projectId/'
    | '/projects/$projectId/$collectionId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  CreateProfileIndexRoute: typeof CreateProfileIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  HomeFoldersFolderIdRoute: typeof HomeFoldersFolderIdRoute
  IntegrationsIntegrationIdIndexRoute: typeof IntegrationsIntegrationIdIndexRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdCollectionIdIndexRoute: typeof ProjectsProjectIdCollectionIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  CreateProfileIndexRoute: CreateProfileIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  HomeFoldersFolderIdRoute: HomeFoldersFolderIdRoute,
  IntegrationsIntegrationIdIndexRoute: IntegrationsIntegrationIdIndexRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdCollectionIdIndexRoute:
    ProjectsProjectIdCollectionIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/auth/",
        "/create-profile/",
        "/home/",
        "/integrations/",
        "/profile/",
        "/projects/",
        "/home/folders/$folderId",
        "/integrations/$integrationId/",
        "/projects/$projectId/",
        "/projects/$projectId/$collectionId/"
      ]
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    },
    "/create-profile/": {
      "filePath": "create-profile/index.tsx"
    },
    "/home/": {
      "filePath": "home/index.tsx"
    },
    "/integrations/": {
      "filePath": "integrations/index.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.tsx"
    },
    "/projects/": {
      "filePath": "projects/index.tsx"
    },
    "/home/folders/$folderId": {
      "filePath": "home/folders/$folderId.tsx"
    },
    "/integrations/$integrationId/": {
      "filePath": "integrations/$integrationId/index.tsx"
    },
    "/projects/$projectId/": {
      "filePath": "projects/$projectId/index.tsx"
    },
    "/projects/$projectId/$collectionId/": {
      "filePath": "projects/$projectId/$collectionId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
