/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProjectsIndexImport } from './routes/projects/index'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as HomeIndexImport } from './routes/home/index'
import { Route as CreateProfileIndexImport } from './routes/create-profile/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as ProjectsProjectIdImport } from './routes/projects/$projectId'

// Create/Update Routes

const ProjectsIndexRoute = ProjectsIndexImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRoute,
} as any)

const CreateProfileIndexRoute = CreateProfileIndexImport.update({
  id: '/create-profile/',
  path: '/create-profile/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectIdRoute = ProjectsProjectIdImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/create-profile/': {
      id: '/create-profile/'
      path: '/create-profile'
      fullPath: '/create-profile'
      preLoaderRoute: typeof CreateProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/auth': typeof AuthIndexRoute
  '/create-profile': typeof CreateProfileIndexRoute
  '/home': typeof HomeIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/projects': typeof ProjectsIndexRoute
}

export interface FileRoutesByTo {
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/auth': typeof AuthIndexRoute
  '/create-profile': typeof CreateProfileIndexRoute
  '/home': typeof HomeIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/projects': typeof ProjectsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/auth/': typeof AuthIndexRoute
  '/create-profile/': typeof CreateProfileIndexRoute
  '/home/': typeof HomeIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/projects/$projectId'
    | '/auth'
    | '/create-profile'
    | '/home'
    | '/profile'
    | '/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/projects/$projectId'
    | '/auth'
    | '/create-profile'
    | '/home'
    | '/profile'
    | '/projects'
  id:
    | '__root__'
    | '/projects/$projectId'
    | '/auth/'
    | '/create-profile/'
    | '/home/'
    | '/profile/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  AuthIndexRoute: typeof AuthIndexRoute
  CreateProfileIndexRoute: typeof CreateProfileIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  AuthIndexRoute: AuthIndexRoute,
  CreateProfileIndexRoute: CreateProfileIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/projects/$projectId",
        "/auth/",
        "/create-profile/",
        "/home/",
        "/profile/",
        "/projects/"
      ]
    },
    "/projects/$projectId": {
      "filePath": "projects/$projectId.tsx"
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    },
    "/create-profile/": {
      "filePath": "create-profile/index.tsx"
    },
    "/home/": {
      "filePath": "home/index.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.tsx"
    },
    "/projects/": {
      "filePath": "projects/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
